twig:
    default_path: '%kernel.project_dir%/templates'
    # config/packages/twig.yaml
    form_themes: ['bootstrap_5_layout.html.twig']
    debug: true
when@test:
    twig:
        strict_variables: true

